const FEATURES = [
  {
    name: 'satellites',
    altitude_km: 800,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: null,
    major: true,
    minScale: 0,
    maxScale: Infinity,
  },
  {
    name: 'space station',
    altitude_km: 400,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 30, dy: -5 },
    major: true,
    minScale: 0,
    maxScale: Infinity,
  },
  {
    name: 'brooklyn to greenport',
    altitude_km: 160,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 80, dy: -20 },
    major: true,
    minScale: 0,
    maxScale: 26,
  },
  {
    name: 'space',
    altitude_km: 100,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 120, dy: -10 },
    major: true,
    minScale: 0,
    maxScale: Infinity,
  },
  {
    name: 'planes & mountains',
    altitude_km: 10,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 140, dy: -2 },
    major: false,
    minScale: 0,
    maxScale: 11,
  },
  {
    name: 'deepest ocean',
    altitude_km: -10,
    color: '#185FA5',
    span_km: 10,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 80, dy: 25 },
    major: false,
    minScale: 0,
    maxScale: 11,
  },
  {
    name: "center of the earth",
    altitude_km: -6350,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: null,
    major: true,
    minScale: 0,
    maxScale: Infinity,
  },
  {
    name: "moon",
    altitude_km: -396700,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: null,
    major: true,
    minScale: 99,
    maxScale: Infinity,
  },
];
