const FEATURES = [
  {
    name: 'satellites',
    altitude_km: 800,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 20, dy: -10 },
    major: true,
    minScale: 0,
    maxScale: 101,
  },
  {
    name: 'space station',
    altitude_km: 400,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 30, dy: -7 },
    major: true,
    minScale: 0,
    maxScale: 101,
  },
  {
    name: 'brooklyn to greenport',
    altitude_km: 160,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 80, dy: -5 },
    major: true,
    minScale: 0,
    maxScale: 26,
  },
  {
    name: 'space',
    altitude_km: 100,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 30, dy: -4 },
    major: true,
    minScale: 0,
    maxScale: 26,
  },
  {
    name: 'planes & mountains',
    altitude_km: 10,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 30, dy: -14 },
    major: false,
    minScale: 0,
    maxScale: 11,
  },
  {
    name: 'deepest ocean',
    altitude_km: -10,
    color: '#185FA5',
    span_km: 10,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 20, dy: 25 },
    major: false,
    minScale: 0,
    maxScale: 11,
  },
  {
    name: "center of the earth",
    altitude_km: -6350,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: null,
    major: true,
    minScale: 0,
    maxScale: Infinity,
  },
  {
    name: "moon",
    altitude_km: -396700,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: null,
    major: true,
    offscreenHint: true,
    minScale: 24,
    maxScale: Infinity,
  },
  {
    name: "nyc",
    altitude_km: 0,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: null,
    major: false,
    minScale: 101,
    maxScale: Infinity,
  },
  {
    name: "tokyo",
    altitude_km: -12700,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: null,
    major: false,
    minScale: 101,
    maxScale: Infinity,
  },
];
