// labelOffset is the taste layer: an optional nudge away from where the code
// would put a label, for balance the code can't know about. Supply only the part
// you mean — dx defaults to the standard leader length, dy to zero — and trust
// the clamp in render.js to keep whatever you write inside the canvas.
// A name may also be an array, to break it across two lines.
const FEATURES = [
  {
    name: 'satellites',
    altitude_km: 800,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dy: -10 },
    major: true,
    minScale: 0,
    maxScale: 101,
  },
  {
    name: 'space station',
    altitude_km: 400,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dy: -21 },
    major: true,
    minScale: 0,
    maxScale: 24,
  },
  {
    name: ['brooklyn to greenport'],
    altitude_km: 160,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: { dy: -25 },
    major: true,
    minScale: 0,
    maxScale: 9,
  },
  {
    name: 'space',
    altitude_km: 100,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dx: 80, dy: -20 },
    major: true,
    minScale: 0,
    maxScale: 26,
  },
  {
    name: 'planes & mountains',
    altitude_km: 10,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dy: -18 },
    major: false,
    minScale: 0,
    maxScale: 4,
  },
  {
    name: 'deepest ocean',
    altitude_km: -10,
    color: '#185FA5',
    span_km: 10,
    labelSide: 'right',
    mirror: true,
    labelOffset: { dy: 25 },
    major: false,
    minScale: 0,
    maxScale: 9,
  },
  {
    name: "center of the earth",
    altitude_km: -6350,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: null,
    major: true,
    minScale: 0,
    maxScale: Infinity,
  },
  {
    name: "moon",
    altitude_km: -396700,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: null,
    major: true,
    offscreenHint: true,
    minScale: 24,
    maxScale: Infinity,
  },
  {
    name: "nyc",
    altitude_km: 0,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: null,
    major: false,
    minScale: 99,
    maxScale: Infinity,
  },
  {
    name: "tokyo",
    altitude_km: -12700,
    color: null,
    span_km: 0,
    labelSide: 'right',
    mirror: false,
    labelOffset: null,
    major: false,
    minScale: 99,
    maxScale: Infinity,
  },
];
