const TERRA = [
  {
    name: 'earth',
    center_km: -6350,
    radius_km: 6350,
    stroke: null,
    strokeWidth_km: 0,
    fill: 'white',
    fillStyle: 'cross-hatch',
    fillWeight: 0.1,
    hachureGap: 4,
    roughness: 0.5,
    opacity: 0.2,
    minScale: 0,
    maxScale: Infinity,
  },
  {
    name: 'habitable zone',
    center_km: -6350,
    radius_km: 6356,
    stroke: '#3B6D11',
    strokeWidth_km: 10,
    fill: null,
    roughness: 0,
    minScale: 0,
    maxScale: Infinity,
  },
  {
    name: 'ocean',
    center_km: -6350,
    radius_km: 6344,
    stroke: '#185FA5',
    strokeWidth_km: 10,
    fill: null,
    roughness: 0,
    minScale: 0,
    maxScale: Infinity,
  },
  {
    name: 'moon',
    center_km: -396700,
    radius_km: 1079.5,
    stroke: null,
    strokeWidth_km: 0,
    fill: 'white',
    fillStyle: 'cross-hatch',
    fillWeight: 0.4,
    hachureGap: 2,
    roughness: 0.5,
    opacity: 0.3,
    minScale: 24,
    maxScale: Infinity,
  },
];
